### ISSUE TITLE
After usual renaming same issue

### ISSUE THREAD

**Issue by Ntemis** [FluBBaOfWard/YieArDS#1]
linking YieArDS.elf
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/12.1.0/../../../../arm-none-eabi/bin/ld: FileHandling.o: in function `loadRoms':
/home/demetris/Desktop/Development/YieArDS/source/FileHandling.c:218: undefined reference to `findFileWithCRC32InZip'
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/12.1.0/../../../../arm-none-eabi/bin/ld: /home/demetris/Desktop/Development/YieArDS/source/FileHandling.c:220: undefined reference to `loadFileWithCRC32InZip'
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/12.1.0/../../../../arm-none-eabi/bin/ld: /home/demetris/Desktop/Development/YieArDS/source/FileHandling.c:228: undefined reference to `findFileWithCRC32InZip'
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/12.1.0/../../../../arm-none-eabi/bin/ld: /home/demetris/Desktop/Development/YieArDS/source/FileHandling.c:228: undefined reference to `findFileWithCRC32InZip'
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/12.1.0/../../../../arm-none-eabi/bin/ld: /home/demetris/Desktop/Development/YieArDS/source/FileHandling.c:230: undefined reference to `loadFileWithCRC32InZip'
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/12.1.0/../../../../arm-none-eabi/bin/ld: FileHelper.o: in function `loadROM':
/home/demetris/Desktop/Development/YieArDS/source/Shared/FileHelper.c:69: undefined reference to `loadFileTypeInZip'
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/12.1.0/../../../../arm-none-eabi/bin/ld: /home/demetris/Desktop/Development/YieArDS/source/Shared/FileHelper.c:89: undefined reference to `cenHead'
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/12.1.0/../../../../arm-none-eabi/bin/ld: /home/demetris/Desktop/Development/YieArDS/source/Shared/FileHelper.c:89: undefined reference to `zipFilename'
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/12.1.0/../../../../arm-none-eabi/bin/ld: /home/demetris/Desktop/Development/YieArDS/source/Shared/FileHelper.c:89: undefined reference to `zipError'
collect2: error: ld returned 1 exit status
make[1]: *** [/opt/devkitpro/devkitARM/ds_rules:54: /home/demetris/Desktop/Development/YieArDS/YieArDS.elf] Error 1

**Comment by FluBBaOfWard** [comment]
Pushed new source.

**Comment by Ntemis** [comment]
/home/demetris/Desktop/Development/YieArDS/source/Cart.s:4:10: fatal error: ARM6809/arm6809mac.h: No such file or directory
    4 | #include "ARM6809/arm6809mac.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Needs ARM6809/ARM6809mac.h ;)

**Comment by FluBBaOfWard** [comment]
Pushed one more fix.

**Comment by Ntemis** [comment]
gtg
